name: Deploy Storage Rules (prod)

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Auth with Google (SA JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Storage rules
        run: firebase deploy --only storage --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
